version: '3.9'
services:

  frontend:
    build: ./frontend
    environment:
      REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
    ports:
      - "3000:3000"
    depends_on:
      - api
      # - ws
      - broker
  broker:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=${BROKER_PORT}
      - REDIS_PASSWORD=${BROKER_PASSWORD}
      - REDIS_DB=${BROKER_DB}
    volumes:
      - broker_data:/data
  api:
    build: ./api
    environment:
      - DB_HOST=db
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - DB_PORT=5432
      - NOSQL_HOST=nosql
      - BROKER_HOST=${BROKER_HOST}
      - BROKER_PORT=${BROKER_PORT}
      - BROKER_PASSWORD=${BROKER_PASSWORD}
      - BROKER_DB=${BROKER_DB}
    ports:
      - "8000:8000"
    depends_on:
      - db
      # - nosql
      - broker

  ws:
    build: ./ws
    environment:
      - DB_HOST=db
      - NOSQL_HOST=nosql
      - BROKER_HOST=${BROKER_HOST}
      - BROKER_PORT=${BROKER_PORT}
      - BROKER_PASSWORD=${BROKER_PASSWORD}
      - BROKER_DB=${BROKER_DB}
    ports:
      - "9000:9000"
    depends_on:
      - db
      - nosql
      - broker
  ai:
    build: ./ai
    environment:
      - DB_HOST=db
      - NOSQL_HOST=nosql
      - BROKER_HOST=${BROKER_HOST}
      - BROKER_PORT=${BROKER_PORT}
      - BROKER_PASSWORD=${BROKER_PASSWORD}
      - BROKER_DB=${BROKER_DB}
    ports:
      - "9100:9100"
    depends_on:
      - db
      - nosql
      - broker

  pose_estimator:
    build: ./pose-estimator
    ports:
      - "8500:8500"
    depends_on:
      - broker

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./api/init.sql:/docker-entrypoint-initdb.d/init.sql

  nosql:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - nosql_data:/data/db

  storage:
    image: minio/minio:latest
    command: server /data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9001:9000"
    volumes:
      - minio_data:/data

volumes:
  db_data:
  nosql_data:
  minio_data:
  broker_data:
