// Code generated by MockGen. DO NOT EDIT.
// Source: participant_query.go

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "api/domain/entity"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockParticipantQueryInterface is a mock of ParticipantQueryInterface interface.
type MockParticipantQueryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockParticipantQueryInterfaceMockRecorder
}

// MockParticipantQueryInterfaceMockRecorder is the mock recorder for MockParticipantQueryInterface.
type MockParticipantQueryInterfaceMockRecorder struct {
	mock *MockParticipantQueryInterface
}

// NewMockParticipantQueryInterface creates a new mock instance.
func NewMockParticipantQueryInterface(ctrl *gomock.Controller) *MockParticipantQueryInterface {
	mock := &MockParticipantQueryInterface{ctrl: ctrl}
	mock.recorder = &MockParticipantQueryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParticipantQueryInterface) EXPECT() *MockParticipantQueryInterfaceMockRecorder {
	return m.recorder
}

// FindCoachesBySport mocks base method.
func (m *MockParticipantQueryInterface) FindCoachesBySport(sport string) ([]entity.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCoachesBySport", sport)
	ret0, _ := ret[0].([]entity.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCoachesBySport indicates an expected call of FindCoachesBySport.
func (mr *MockParticipantQueryInterfaceMockRecorder) FindCoachesBySport(sport interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCoachesBySport", reflect.TypeOf((*MockParticipantQueryInterface)(nil).FindCoachesBySport), sport)
}

// FindParticipantByID mocks base method.
func (m *MockParticipantQueryInterface) FindParticipantByID(participantID string) (*entity.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindParticipantByID", participantID)
	ret0, _ := ret[0].(*entity.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindParticipantByID indicates an expected call of FindParticipantByID.
func (mr *MockParticipantQueryInterfaceMockRecorder) FindParticipantByID(participantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindParticipantByID", reflect.TypeOf((*MockParticipantQueryInterface)(nil).FindParticipantByID), participantID)
}

// FindParticipantsByChatID mocks base method.
func (m *MockParticipantQueryInterface) FindParticipantsByChatID(chatID string) ([]entity.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindParticipantsByChatID", chatID)
	ret0, _ := ret[0].([]entity.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindParticipantsByChatID indicates an expected call of FindParticipantsByChatID.
func (mr *MockParticipantQueryInterfaceMockRecorder) FindParticipantsByChatID(chatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindParticipantsByChatID", reflect.TypeOf((*MockParticipantQueryInterface)(nil).FindParticipantsByChatID), chatID)
}

// FindParticipantsByIDs mocks base method.
func (m *MockParticipantQueryInterface) FindParticipantsByIDs(ids []string) ([]entity.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindParticipantsByIDs", ids)
	ret0, _ := ret[0].([]entity.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindParticipantsByIDs indicates an expected call of FindParticipantsByIDs.
func (mr *MockParticipantQueryInterfaceMockRecorder) FindParticipantsByIDs(ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindParticipantsByIDs", reflect.TypeOf((*MockParticipantQueryInterface)(nil).FindParticipantsByIDs), ids)
}
