root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main"
  full_bin = ""
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "frontend"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  delay = 1000 # ms
  stop_on_error = true
  log = "build-errors.log"

[run]
  cmd = "./tmp/main"
  log = "run-errors.log"
  delay = 1000 # ms

[misc]
  clean_on_exit = true
